sudo: required
services:
  - docker

before_install:
  - docker build -t vishwajeet33/dockernew -f Dockerfile.dev .

script:
  - docker run vishwajeet33/dockernew npm run test -- --coverage
















